// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avweluqlkwnlovmzhlml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2d2VsdXFsa3dubG92bXpobG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjAyMTUsImV4cCI6MjA2Nzg5NjIxNX0.sjwlGIvHwanyvUfO3xv0uvJ-t6iHt5WWf2UsGegFYBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});